### ISSUE TITLE
Extract search results & music tracks from raw json (Youtube Music)

### ISSUE THREAD

**Issue by madeyoga** [madeyoga/ytpy#4]
https://github.com/madeyoga/ytpy/blob/10c2915476e58ea31c0c131afdfe42b53c1135e1/ytpy/youtube.py#L160-L171

### Objective
Extract search results & music tracks from raw json to python List of dictionaries

### Wanted/Required data
- title
- videoId
- author
- duration

### Starting point
- Clone repo & change directory & Install development
```
pip install .
```
- Get `yt_music_key`
  - Open music.youtube.com & search something, 
  - Open network, & look for the search request, use the `key` parameter value as `yt_music_key`

- Raw Json
```py
from ytpy import YoutubeClient
import asyncio
import aiohttp


async def main(loop):
    session = aiohttp.ClientSession()

    client = YoutubeClient(session, yt_music_key="<youtube-music-key>")

    response = await client.search_music(q='black suit')

    # Response is a raw json
    print(response)

    await session.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
```

- Start parsing

**Comment by sushantk-dev** [comment]
I have made a pull a request.can you check if it is fine?
